### ISSUE TITLE
Handle bug reset data on version IOS 17.1 (Round 4)

### ISSUE THREAD

**Issue by nguyenduythuc** [Koniverse/SubWallet-Mobile#1195]
What to do:
- Web runner:
  + Cache localstorage & index db into ram
  + Add backup & restore function
  + Add event require_restore when start up
- Mobile:
  + Backup data when start up + event update data (example: add account, create transaction)
  + Restore when require_restore
  + Only apply for ios 17
  + Show backup/restore log in debug mode

**Comment by Sokol142196** [comment]
@saltict please update alert to disclaim
- Header: Back up your seed phrase
- Content: Due to the instability of iOS 17, we highly recommend that you back up your seed phrase and reinstall SubWallet for better performance.
- Button: Learn how to back up --> link đến https://docs.subwallet.app/main/mobile-app-user-guide/account-management/export-and-backup-an-account
