### ISSUE TITLE
Issue with sending NFTs

### ISSUE THREAD

**Issue by mezrin** [Koniverse/SubWallet-Mobile#1349]
I tried to send an NFT and the app displayed the error.
Sending with the polkadot-js works just fine

NFT was issued on Kusama assets hub
Pallet uniques

<img src="https://github.com/Koniverse/SubWallet-Mobile/assets/2777812/0e4cd945-6cd6-46fa-9a80-f92afdb92f64" width="135" height="300" />

**Comment by saltict** [comment]
Hi @mezrin, 

As you can see on the screen, the cause of this problem is that the connection to RPC is unstable to check if the balance is enough to pay the transaction fee.

In this case, the user will re-enable the connection or change the RPC endpoint. This situation is often observed with RPC endpoints that are unstable or rate limits that are too low.

We do not have any effective solutions to completely solve this problem and we look forward to finding ways to handle them. Let me know your opinion about this problem, maybe we can find a good solution.

**Comment by mezrin** [comment]
Ah, got it. Yes, it's not a wallet-related issue.

In my experience the only way to solve this kind of issues is to have a proper indexer (block explorer).
Indexer must provide access to the blockchain` current state (storage) via REST / GraphQL API - in addition to historical data like events / blocks / transactions.
In our company we are working on such an indexer for substrate-based chains. Maybe it will be available later this year.
